name: Update calendar

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update calendar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Run script
      run: uv run fedora-release-schedule-ical.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto commit - Calendar was updated
